format: '&8(&aPuzzle&8) &b&lUnscramble the word! &7The word is &e$word'
interval: 600
words:
- 'harry potter'
- 'crystal ball'
- 'spell'
- 'magic'
- 'lethifold'
- 'flobberworm'
- 'mandrake'
- 'horcrux'
- 'lumos'
- 'meteolojinx recanto'
- 'porpentina'
- 'seraphina picquery'
- 'hippogriff'
- 'niffler'
- 'great hall'
- 'godrics hollow'
- 'beauxbatons'
- 'hogwarts'
- 'durmstrang'
- 'ilvermorny'
- 'charms'
- 'divination'
- 'potions'
- 'herbology'
- 'mandrake'
- 'gillyweed'
- 'croissant'
- 'baguette'
- 'macusa'
- 'grindelwald'
- 'occamy'
- 'avada kedavra'
- 'dumbledore'
- 'scamander'
- 'goldstein'
- 'triwizard cup'
- 'ministry of magic'
- 'rowlings realm'
- 'whomping willow'
- 'death eater'
- 'transfiguration'
- 'headmaster'
- 'dementor'
- 'gringotts'
- 'dobby'
- 'basilisk'
- 'obscurial'
- 'weasley'
- 'magizoology'
- 'bowtruckle'
- 'demiguise'
- 'thunderbird'
- 'billywig'
- 'swooping evil'
- 'erumpent'
- 'nundus'
- 'azkaban'
- 'leaky cauldron'
- 'honeydukes'
- 'ollivanders'
- 'knockturn'
- 'lovegood'
- 'rubeus hagrid'
